version: '3.8'

services:

  db:
    image: postgres:alpine
    env_file:
      - .env_docker
    command: -p 5431
    ports:
      - "5431:5431"
    expose:
      - 5431

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn poll.wsgi:application --bind 0.0.0.0:8005 --access-logfile -"
    volumes:
      - static_value:/djangopoll/static/
      - ./media:/djangopoll/media/
    restart: always
    ports:
      - "8005:8005"
    depends_on:
      - db
    env_file:
      - .env_docker

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_value:/djangopoll/static/
    depends_on:
      - web

volumes:
  static_value:
  media_value: